FROM ngnix:alpine
COPY ./config/nginx/app.conf /etc/nginx/conf.d/app.conf

COPY ./var/www/html /var/www/html
#COPY ./config/nginx/app.conf /etc/nginx/conf.d/app.conf
#COPY nginx.conf /etc/nginx/conf.d/nginx.conf

